SECRET_KEY: 'django-insecure-test-key-for-development-purposes-only'
DEBUG: True
ALLOWED_HOSTS: 'localhost 127.0.0.1 [::1]'
CSRF_TRUSTED_ORIGINS: 'http://localhost http://127.0.0.1'
DATABASE_ENGINE: 'django.db.backends.sqlite3'
DATABASE_HOST: ''
DATABASE_USER: ''
DATABASE_PASS: ''
DATABASE_DB: ':memory:'